### ISSUE TITLE
Add an option to count words instead of lines

### ISSUE THREAD

**Issue by Olivier-Berg** [Jonxslays/xloc#1]
^

**Comment by Jonxslays** [comment]
The original purpose of this program was just to count lines as represented by the package name x lines of code. While i'm not opposed, i'm not convinced it's necessary. What are your thoughts @parafoxia

**Comment by parafoxia** [comment]
`wc` has it, so in theory there's no reason not to. Although the name is literally `x lines of code` so depends.

**Comment by Jonxslays** [comment]
This is true. wc is word count though and they do lines lol. I'll take a look at this, unless one of you two wants to give it a go. I am picturing a `-w` flag that just returns the word count instead.

**Comment by parafoxia** [comment]
I don't have any objections to that.
